import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../../core/enums.dart';
import '../../../core/utils/formatters.dart';
import '../../../core/utils/money.dart';
import '../../settings/domain/shop_profile.dart';
import '../domain/report_models.dart';
import '../domain/report_range.dart';

/// Builds an A4 PDF of a sales report, suitable for sharing with the CA. It
/// paginates automatically and lists every bill with its number and details.
///
/// Amounts use an "Rs" prefix (not the ₹ glyph) because the built-in PDF fonts
/// don't include the rupee symbol.
Future<Uint8List> buildReportPdf(
  ReportDashboard data,
  ReportRange range,
  ShopProfile shop,
  DateTime generatedAt, {
  required List<ReportBillRow> bills,
}) async {
  final doc = pw.Document();
  final s = data.sales;

  // Money is an extension type (an int at runtime), so this must be statically
  // typed as Money — a `dynamic` call would fail to find `formattedPlain`.
  String rs(Money v) => 'Rs ${v.formattedPlain}';

  doc.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      footer: (context) => pw.Padding(
        padding: const pw.EdgeInsets.only(top: 8),
        child: pw.Text(
          'Generated by PSG POS · page ${context.pageNumber} of '
          '${context.pagesCount}',
          style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey),
        ),
      ),
      build: (context) => [
        pw.Text(
          shop.shopName,
          style: const pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold),
        ),
        if (shop.address != null && shop.address!.trim().isNotEmpty)
          pw.Text(shop.address!.trim()),
        if (shop.phone != null && shop.phone!.trim().isNotEmpty)
          pw.Text('Ph: ${shop.phone!.trim()}'),
        if (shop.hasGst) pw.Text('GSTIN: ${shop.gstNumber!.trim()}'),
        pw.Divider(),
        pw.SizedBox(height: 8),
        pw.Text(
          '${range.label} Sales Report',
          style: const pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
        ),
        pw.Text('Generated ${Formatters.dateTime(generatedAt)}'),
        pw.SizedBox(height: 16),
        _kvTable([
          ['Total sales', rs(s.totalSales)],
          ['Bills', '${s.billCount}'],
          ['Items sold', '${s.itemsSold}'],
          ['Average bill', rs(s.averageBill)],
          ['Discounts given', rs(s.totalDiscount)],
        ]),
        pw.SizedBox(height: 20),

        // ── Bill-by-bill detail ──────────────────────────────
        pw.Text(
          'Bills',
          style: const pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 6),
        if (bills.isEmpty)
          pw.Text('No bills in this period.')
        else
          pw.TableHelper.fromTextArray(
            headerStyle: const pw.TextStyle(fontWeight: pw.FontWeight.bold),
            cellStyle: const pw.TextStyle(fontSize: 9),
            headers: ['Invoice', 'Date', 'Type', 'Payment', 'Total'],
            cellAlignments: const {
              0: pw.Alignment.centerLeft,
              1: pw.Alignment.centerLeft,
              2: pw.Alignment.center,
              3: pw.Alignment.center,
              4: pw.Alignment.centerRight,
            },
            data: [
              for (final b in bills)
                [
                  b.invoiceNo,
                  Formatters.receiptDateTime(b.billedAt),
                  b.isGst ? 'GST' : 'Plain',
                  b.paymentMethod.label,
                  rs(b.total),
                ],
            ],
          ),

        if (data.bestSellers.isNotEmpty) ...[
          pw.SizedBox(height: 20),
          pw.Text(
            'Best sellers',
            style: const pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 6),
          pw.TableHelper.fromTextArray(
            headers: ['Item', 'Qty', 'Revenue'],
            headerStyle: const pw.TextStyle(fontWeight: pw.FontWeight.bold),
            cellAlignments: const {
              0: pw.Alignment.centerLeft,
              1: pw.Alignment.center,
              2: pw.Alignment.centerRight,
            },
            data: [
              for (final b in data.bestSellers)
                [b.name, '${b.qtySold}', rs(b.revenue)],
            ],
          ),
        ],
      ],
    ),
  );

  return doc.save();
}

pw.Widget _kvTable(List<List<String>> rows) {
  return pw.Table(
    columnWidths: const {
      0: pw.FlexColumnWidth(3),
      1: pw.FlexColumnWidth(2),
    },
    children: [
      for (final r in rows)
        pw.TableRow(
          children: [
            pw.Padding(
              padding: const pw.EdgeInsets.symmetric(vertical: 4),
              child: pw.Text(r[0]),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.symmetric(vertical: 4),
              child: pw.Text(
                r[1],
                textAlign: pw.TextAlign.right,
                style: const pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
            ),
          ],
        ),
    ],
  );
}
